In [1]:
# 넘파이 임포트
import numpy as np

In [2]:
# 버전 조회
np.__version__

'1.21.5'

In [3]:
# arange(:차례대로 숫자 생성) 변수 생성
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [4]:
# .newaxis 로 새로운 차원에 배열 넣어줌
a2 = a[np.newaxis,:]
a2

array([[0, 1, 2, 3, 4, 5]])

In [5]:
# shape으로 배열의 크기 확인 (몇 행의, 몇 열인지)
a2.shape

(1, 6)

In [6]:
# `'1'` 대신 `1.` 넣으면 데이터 타입 float64
a = np.array(['1',2,3,4,5,6])

In [7]:
# 배열에 데이터 타입 확인
a.dtype

dtype('<U11')

In [8]:
# 배열의 차원이 몇 차원인지 조회
a.ndim

1

In [9]:
a.shape

(6,)

In [10]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [11]:
a.ndim

2

In [12]:
a.shape

(3, 4)

In [13]:
# 어레이 자체를 호출
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
# array 내부 내용 출력
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
# a 어레이의 0번째 인덱스 값
a[0]

array([1, 2, 3, 4])

In [16]:
# 1행 4열의 값
a[0,3]

4

In [17]:
# 모든 행의 4열값 전부 호출
a[:,3]

array([ 4,  8, 12])

In [18]:
np.array([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]])

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]])

In [19]:
# int8, 16, 32, 64 다른것들도 있다.
# np.zeros 를 사용해서 배열 만들면 내용물 `0`이 들어간 배열 생성해준다.
# 0으로 가득찬 array를 생성
# zeros는 메모리를 할당받아 0으로 초기화한 뒤에 반환하지만,
# empty는 메모리 할당만 받고 초기화 없이 반환한다.
np.zeros((2,3),dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [20]:
# np.ones 를 사용해서 배열 만들면 내용물 `1.`이 들어간 배열 생성해준다.
# 1로 가득찬 array를 생성
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
# np.empty 를 사용해서 배열 만들면 내용물 `0.`이 들어간 배열 생성해준다.
# empty는 초기화되지 않은 값으로 zeros나 ones와 마찬가지로 배열을 생성해줍니다.
# 주의해야 할 것은 메모리도 초기화되지 않기 때문에 예상하지 못한 쓰레기 값이 들어가 있습니다.
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [23]:
# `linspace(0,10,5)` : 0과 10까지의 중간값을 포함한, 총 5개의 데이터 넣은 배열 생성
# `linspace( , , )` 구간 시작점, 구간 끝점, 구간 내 숫자 개수 3가지를 순서대로 채워주시면 됩니다.
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [25]:
# sort 문법으로 순서 정렬해줌 인덱스 번호 -1로 음수부터 넣으면 순서 반대로 정렬됨.
np.sort(arr)[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1])

In [26]:
a = np.array([[1,4],[3,1]])
a

array([[1, 4],
       [3, 1]])

In [27]:
# 정렬하면 list 안에 데이터 이렇게 만들어줌
# axis=1 이면 열 기준으로 정렬해줌 (오른쪽 방향)
np.sort(a,axis=1)

array([[1, 4],
       [1, 3]])

In [28]:
# axis=0 이면 행 기준으로 정렬해줌 (아래 방향)
np.sort(a,axis=0)

array([[1, 1],
       [3, 4]])

In [29]:
x = np.array([3, 1, 2])

In [30]:
# 어레이 데이터를 순서 정렬했을 때의 인덱스 값을 알려줌
# argsort()는 아래와 같이 정렬되기 전의 인덱스를 리스트 형태로 반환합니다.
# 이를 이용해 데이터베이스에서 가져온 서로 다른 테이블의 값을 정렬할 수 있습니다.
np.argsort(x)

array([1, 2, 0], dtype=int64)

In [31]:
# 제일 큰 값의 인덱스를 출력해라
# : [2] 인덱스
np.argmax(x)

0

In [32]:
x = np.array([[0, 3], [2, 2]])

In [33]:
x

array([[0, 3],
       [2, 2]])

In [34]:
# `argsort` 는 어레이 x를 정렬하는 인덱스의 어레이를 반환
# axis=-1 이 기본값임
np.argsort(x, axis=-1)

array([[0, 1],
       [0, 1]], dtype=int64)

In [35]:
np.argsort(x, axis=1)
# axis=-1 때와 같음

array([[0, 1],
       [0, 1]], dtype=int64)

In [36]:
np.argsort(x, axis=0)

array([[0, 1],
       [1, 0]], dtype=int64)

In [37]:
# 3차원 행렬에서는!
a = np.array([[[1, 2, 3, 4]]])
b = np.array([[[5, 6, 7, 8]]])

In [38]:
# concatenate : 합치기
# axis=0이 기본값
np.concatenate((a,b),axis=0)

array([[[1, 2, 3, 4]],

       [[5, 6, 7, 8]]])

In [39]:
np.concatenate((a,b),axis=1)

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [40]:
np.concatenate((a,b),axis=2)

array([[[1, 2, 3, 4, 5, 6, 7, 8]]])

In [41]:
a.ndim

3

In [42]:
a.shape
# 3차원 배열에서 1행, 4열짜리가 하나있음.

(1, 1, 4)

In [43]:
a.size

4

In [44]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [45]:
# np.reshape(변경할 배열, 차원) 또는 배열.reshape(차원)으로 사용 할 수 있으며, 
# 현재의 배열의 차원(1차원,2차원,3차원)을 변경하여 행렬을 반환하거나 하는 경우에 많이 이용되는 함수이다
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [46]:
a.reshape(2,2)
# 이때는 크기가 안맞게 모양 잡아달라고 해서 오류 나는게 맞음

ValueError: cannot reshape array of size 6 into shape (2,2)

In [51]:
# 이 reshape 으로 차원 모양을 바꿔서 활용함
# 모양 바꿀 땐 구조에 맞출 크키가 모자라거나 남으면 안된다.
np.reshape(a,(2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
a = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
a.shape

In [ ]:
# `:` : 처음부터 끝까지 쓰겠단 뜻
a2 = a[np.newaxis,:]
a2

In [ ]:
a2.shape

In [ ]:
a3 = a[:,np.newaxis]

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a

In [ ]:
# 이럴땐 행으로 확장 됨
b = np.expand_dims(a,axis=0)

In [ ]:
b

In [ ]:
aa = a3.reshape((3,2))
aa

In [ ]:
a4 = np.expand_dims(aa,axis=0)
a4.shape

In [ ]:
a4 = np.expand_dims(aa,axis=1)
a4.shape

In [ ]:
a4 = np.expand_dims(aa,axis=2)
a4.shape

In [ ]:
a4 = np.expand_dims(aa,axis=3)
a4.shape
# 3차원이 최대라서 axis 지정 가능한 범위 초과해서 오류나는게 정상

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
a

In [ ]:
a.ndim

In [ ]:
a.shape

In [ ]:
a[a>=5]

In [ ]:
a[a%2==0]

In [ ]:
# 이렇게 비교연산자를 함께 쓸 때는 괄호로 우선순위 맞춰줘야함.
a[(a>2) & (a<11)]

In [ ]:
# or 연산자
a[(a>5)|(a==5)]

In [ ]:
# .nonzero 함수는 0이 아닌 요소의 인덱스를 얻을 수 있는 심플한 함수이다
# 이 함수를 통해 반환되는 것은 각 축마다 0아 이닌 요소의 인덱스를 1차원 배열이다.
# 조건을 넣으면 조건에 맞는 행렬값을 리턴 함
b = np.nonzero(a<5)
b
#  (*여기는 행값 : array([0, 0, 0, 0], dtype=int64), * 여기는 열 값 : array([0, 1, 2, 3], dtype=int64))

In [ ]:
# zip() : 두 그룹의 데이터를 서로 엮어주는 파이썬의 내장 함수
# 이렇게 list랑 같이 쓴다.
list(zip(b[0],b[1]))

In [ ]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr1 = a[3:8]

In [ ]:
a

In [ ]:
arr1
# array가 arr1의 인덱스 값을 참고해서 보여주는거임

In [ ]:
arr1[0]=14
#그래서 이렇게 array 에서 인덱스 지정해서 값을 바꾸면

In [ ]:
a
# a 안에 데이터도 바뀌는 걸 볼 수 있음.

In [ ]:
arr1

In [ ]:
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])

- np.concatenate 함수를 통해서도 두 개의 배열을 붙일 수 있다.
위와 같이 axis=1로 concatenate을 할 경우 열을 추가하는 동작을 하고,
axis=0으로 concatenate을 할 경우 행을 추가하게 된다.
hstack/vstack과 동일하게
여기서도 마찬가지로 추가할 때의 row/col의 개수가 맞아야지 추가할 수 있다.

- hstack은 horizontal stack의 약자로 두 개의 배열을 좌우로 붙여주는 함수이다.
좌우로 붙여야하기 때문에 row의 개수는 동일해야 한다.

- vstack은 vertical stack의 약자로 두 개의 배열을 위아래로 붙여주는 함수이다.
위아래로 붙여야하기 때문에 col의 개수는 동일해야 한다.


In [ ]:
np.concatenate((a1,a2),axis=0)

In [ ]:
np.concatenate((a1,a2),axis=1)

In [ ]:
np.vstack((a1,a2))

In [ ]:
np.hstack((a1,a2))
# [3,2] 배열 추가해서 여기선 오류나는게 정상

In [ ]:
x = np.arange(1, 25).reshape(2, 12)
x

- np.split(ary, indices_or_sections, axis=0)
"ary" : 넘파이 객체로 쪼갤 배열입니다.

"indices_or_sections" : 만약 이 인수가 정수형 N이라면 쪼개지는 배열이 N개의 동일한 값을 가집니다. 만약, 나누는 것이 불가능하다면 오류가 발생합니다. 만약, 이 인수가 정렬된 1차원 배열이라면 배열의 요소값을 기준으로 값을 나눕니다.

"axis" : 나눌 방향을 의미합니다.

indices_or_sections에 배열로 넣을 때는 어떤 인덱스를 기준으로 쪼갤것인지를 생각하시면 됩니다.
따라서 `np.hsplit(x, (3, 4))`는 3번, 4번 인덱스에서 끊어서 각각 배열 만들어줌.

- np.hsplit(ary, indices_or_sections)
 이 함수는 split 함수를 axis=1 방향으로 쪼개는 것
 
- np.vsplit(ary, indices_or_sections)
 이 함수는 split 함수를 axis=0 방향으로 쪼개는 것
 
- np.dsplit(ary, indices_or_sections)
 이 함수는 다른 함수들과는 다르게 3차원 이상의 배열이 반드시 들어가야합니다. 즉, axis=2 방향으로 쪼개는 함수

In [ ]:
np.hsplit(x, 3)

In [ ]:
np.hsplit(x, (3, 4))

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
b1 = a[0, :]
b1

b1[0] = 99
b1

a

In [ ]:
b2 = a.copy()

In [ ]:
b2[0] = 55
b2
a

In [ ]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)

In [ ]:
data

In [ ]:
ones

In [ ]:
data + ones

In [ ]:
# 이렇게 넘파이에서 배열 계산식 활용하면
# 쓸데 없는 for문 안만들어도 돼서 시간 절약 많이 된다.
# 그냥 바로 사칙연산 바로 하면 된다.

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
a.sum()

In [ ]:
b = np.array([[1, 1], [2, 2]])

In [ ]:
b.sum()

In [ ]:
# 그냥 더하니까 위에와 같이 전체 값 합산 됐음
# 아래처럼 축을 정하면

In [ ]:
b

In [ ]:
b.sum(0)

In [ ]:
b.sum(1)

In [ ]:
#위에서 처럼 기준으로 지정된 축에 대해서 더해짐

In [ ]:
data = np.array([1.0, 2.0])

In [ ]:
data

In [ ]:
# 데이터 값 확장됨.
data * 1.6

In [ ]:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])

In [ ]:
b = np.array([1.0, 2.0, 3.0])

In [ ]:
a+b

In [ ]:
c=np.array([8])

In [ ]:
a*c

In [ ]:
# 난수 생성
# 시드값 고정해서 하면 난수 패턴이 정해져있기 때문에 사실상 고정된 데이터가 나옴
rng = np.random.default_rng(1)

In [ ]:
rng.random(3)

In [ ]:
# 정수 만들어주는 명령.
# : 원래는 1~4 사이의 정수 값을 추출해주는 명령이지만 (endpoint 값 미지정, false일때)
# 이렇게 endpoint 값 True로 해서 5까지의 범위도추출할 수도 있다.
rng.integers(1,5,endpoint=True)

In [ ]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [ ]:
# 고유의 값들만, 고유 값들의 개수를 알아보는 방법.
# return_index=True 로 중복되는 값 빼고 고유 값들만 추출
# return_inverse=True 로 고유 데이터들이 처음 선언된 인덱스값 추출
# return_counts=True 로 고유 데이터들의 총 개수를 알려줌
np.unique(a,return_index=True,return_inverse=True,return_counts=True)

In [ ]:
data = np.arange(1,7).reshape(2,3)

In [ ]:
data

In [ ]:
# 행과 열의 데이터 위치를 고대로 바꿔줌
data.transpose()

In [ ]:
data.T

In [ ]:
arr = np.array([1,2,3,4,9,6,7,8])

In [ ]:
# 배열 뒤집기 (데이터 값들을 인덱스값 반대순으로 그대로 뒤집어줌)
np.flip(arr)

In [ ]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
arr_2d

In [ ]:
# axis 차원값 지정해서 뒤집어주는 것도 가능
np.flip(arr_2d,axis=1)

In [ ]:
x

In [ ]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
x

In [ ]:
# 다차원 배열 형태 변경 및 병합

# 배열들을 무조건 1차원으로 평평하게 합쳐줌.
x.flatten()

In [ ]:
# reshape((1,-1)) : 1행 짜리로, 열 형태는 존재하는 열 개수 그대로 가져온다.(지금은 4열까지 있으니 인덱스 3넣은것과 같다.)
# 뒤에 `()[0]` 넣어주면 위에처럼 1차원 배열로 담김
x.reshape(x,(1,-1))

- 위와 같이 배열을 병합할때는 병합된 데이터가 원본에 영향을 미치지만
- ravel 복사는 얕은 복사이기 때문에 원본 데이터에 변경된 배열 데이터가 반영되지 않는다.

In [ ]:
x.reshape??
# ?로 물음표 한개만 하거나 이렇게 두개 적어주면 쉬프트+탭 설명서 나온다.

In [ ]:
def double(a):
    '''
    함수 사용법
    double(arr)
    '''
    return a*2

In [ ]:
double?

In [ ]:
double??

In [ ]:
# 이렇게 도움말음 첨부해줘야 협업 할 때 좋다.