## 교차검증
검증 데이터를 교차로 지정하여 더 다양한 형태로 평가해서 예측 정확도를 검증하고 학습하는 과정.
- 다만 너무 학습한 데이터에만 최적화 되어 과적합에 취약 할 수 있음.

#### K폴드 교차검증

In [1]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np
from sklearn.model_selection import StratifiedKFold

In [2]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)
kfold = KFold(n_splits=5,shuffle=True)

In [3]:
cv_accuracy = []
n_iter = 0

# 데이터 건수 150개
for train_index,test_index in kfold.split(iris.data):
    # print(train_index)
    # print(test_index)
    X_train,X_test = iris.data[train_index],iris.data[test_index]
    y_train,y_test = iris.target[train_index],iris.target[test_index]
    # 학습
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    accuracy = accuracy_score(y_test,pred)
    cv_accuracy.append(accuracy)
    print(n_iter,accuracy)
    print(y_test)

1 1.0
[0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2]
2 0.9333333333333333
[0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2]
3 0.9666666666666667
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2]
4 0.9
[0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2]
5 0.9333333333333333
[0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2]


In [4]:
# 각 회차별로 나온걸 넘파이에 라운드 함.
np.round(np.mean(cv_accuracy),4)

0.9467

In [5]:
# 레이블 값 (타겟 값이) 얼마나 있고 몇 개 있는지 확인하기 - value.count

In [6]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
data = load_iris(as_frame=True)

In [8]:
data.target.value_counts()

0    50
1    50
2    50
Name: target, dtype: int64

In [9]:
kfold = KFold(n_splits=3,shuffle=True)
cv_accuracy = []
n_iter = 0

# 데이터 건수 150개
for train_index,test_index in kfold.split(iris.data):
    # print(train_index)
    # print(test_index)
    X_train,X_test = iris.data[train_index],iris.data[test_index]
    y_train,y_test = iris.target[train_index],iris.target[test_index]
    # 학습
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    accuracy = accuracy_score(y_test,pred)
    cv_accuracy.append(accuracy)
    print(n_iter,accuracy)
    print(y_test)

1 0.94
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]
2 0.92
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]
3 0.96
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [10]:
kfold = StratifiedKFold(n_splits=3,shuffle=False)
cv_accuracy = []
n_iter = 0

#
iris = load_iris(as_frame=True)

# 위에는 비율을 안따짐
# 여기선 비율을 따지기 때문에 x값과 y값도 넣어줘야함.
for train_index,test_index in kfold.split(iris.data, iris.target):
    # print(train_index)*
    # print(test_index)
    X_train,X_test = iris.data.iloc[train_index],iris.data.iloc[test_index]
    y_train,y_test = iris.target.iloc[train_index],iris.target.iloc[test_index]

    # 비율까지 따져서 잘라준다는 것 확인 
    print(type(iris.target))
    print('검증데이터 분포:',y_test.value_counts())
    
    # 학습
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    accuracy = accuracy_score(y_test,pred)
    cv_accuracy.append(accuracy)
    print(n_iter,accuracy)
    # print(y_test)

<class 'pandas.core.series.Series'>
검증데이터 분포: 0    17
1    17
2    16
Name: target, dtype: int64
1 0.98
<class 'pandas.core.series.Series'>
검증데이터 분포: 0    17
2    17
1    16
Name: target, dtype: int64
2 0.94
<class 'pandas.core.series.Series'>
검증데이터 분포: 1    17
2    17
0    16
Name: target, dtype: int64
3 0.98


#### 교차검증을 보다 더 간편하게 해주는 사이킷런 API : cross_val_score()
대신 모델의 성능만 알 수 있고
다른 용도로 사용하기 힘들어서 수치 확인 할 때만 주로 사용함.

In [11]:
from sklearn.model_selection import cross_val_score

In [12]:
dt_clf = DecisionTreeClassifier(random_state=156)
iris = load_iris()
# cv 파라미터처럼 사람이 직접 넣어주어야 하는 파라미터를 하이퍼 파라미터 라고 한다.
cross_val_score(dt_clf,iris.data,iris.target,cv=3)

array([0.98, 0.94, 0.98])

- 하이퍼 파라미터
: 아래에서 처럼 cv 파라미터처럼 사람이 직접 넣어주어야 하는 파라미터를 하이퍼 파라미터 라고 한다.
 머신러닝 보다 딥러닝에서 이 영향을 덜 받는다.

cross_val_score(dt_clf,iris.data,iris.target,cv=3)

In [18]:
# 파라미터 값 사전 지정
grid_param = {
    'max_depth':[1,2,3],
    'min_samples_split':[2,3] 
    # 6번에 걸쳐서 작업함
}

In [19]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
# from sklearn.datasets import load_iris
import pandas as pd

In [20]:
iris = load_iris()
# 데이터 분리
X_train,X_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.2,random_state=121)

In [30]:
dtree = DecisionTreeClassifier()
# 파라미터 분리 되면서 작업된 6번의 작업과 교차검증(cv=3) 까지하면 총 18번의 학습을 해본다.
grid_dtree = GridSearchCV(dtree,grid_param,cv=3,refit=True)

In [32]:
grid_dtree.fit(X_train,y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]})

In [33]:
grid_dtree.predict(X_test)

array([1, 2, 1, 0, 0, 1, 1, 1, 1, 2, 2, 1, 1, 0, 0, 2, 1, 0, 2, 0, 2, 2,
       1, 1, 1, 1, 0, 0, 2, 2])

In [35]:
df = pd.DataFrame(grid_dtree.cv_results_)

In [36]:
df.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_max_depth', 'param_min_samples_split', 'params',
       'split0_test_score', 'split1_test_score', 'split2_test_score',
       'mean_test_score', 'std_test_score', 'rank_test_score'],
      dtype='object')

In [42]:
df[['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_max_depth', 'param_min_samples_split', 'params',
       'split0_test_score', 'split1_test_score', 'split2_test_score',
       'mean_test_score', 'std_test_score', 'rank_test_score']]

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.001315      0.000439         0.000548        0.000412   
1       0.001067      0.000040         0.000499        0.000406   
2       0.001024      0.000037         0.000340        0.000481   
3       0.001399      0.000451         0.000334        0.000473   
4       0.001321      0.000456         0.000662        0.000468   
5       0.000805      0.000219         0.001056        0.000087   

  param_max_depth param_min_samples_split  \
0               1                       2   
1               1                       3   
2               2                       2   
3               2                       3   
4               3                       2   
5               3                       3   

                                     params  split0_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}              0.700   
1  {'max_depth': 1, 'min_samples_split': 3}              0.700   
2  {'max_depth': 2, 'min_samples_split': 2}              0.925   
3  {'max_depth': 2, 'min_samples_split': 3}              0.925   
4  {'max_depth': 3, 'min_samples_split': 2}              0.975   
5  {'max_depth': 3, 'min_samples_split': 3}              0.975   

   split1_test_score  split2_test_score  mean_test_score  std_test_score  \
0                0.7               0.70         0.700000    1.110223e-16   
1                0.7               0.70         0.700000    1.110223e-16   
2                1.0               0.95         0.958333    3.118048e-02   
3                1.0               0.95         0.958333    3.118048e-02   
4                1.0               0.95         0.975000    2.041241e-02   
5                1.0               0.95         0.975000    2.041241e-02   

   rank_test_score  
0                5  
1                5  
2                3  
3                3  
4                1  
5                1

In [43]:
grid_dtree.best_params_

{'max_depth': 3, 'min_samples_split': 2}

In [44]:
grid_dtree.best_score_

0.975

In [46]:
pred = grid_dtree.best_estimator_.predict(X_test)

In [47]:
accuracy_score(y_test,pred)

0.9666666666666667

In [48]:
# 검증용 데이터로하니까 강사님은 100퍼가 나옴 랜덤 스테이트가 각자 다르기 때문에 다 다른게 맞음.